### PR TITLE
Improve polymorphic docs

### PR DESCRIPTION
**Pull request by jannyHou**
connect to strongloop/loopback-datasource-juggler#1298

STILL IN PROGRESS

As we discussed in PR https://github.com/strongloop/loopback.io/pull/381, in this PR I will address comments from @crandmck and @ebarault 

- [x] Change model name
- [x] Refactor definition format
- [ ] Add embedOne/embedsMany polymorphic relation

### CODE REVIEW

**Comment by crandmck** [comment]
@jannyHou Any progress on this?  What's current status?

**Comment by jannyHou** [comment]
@crandmck sorry I have been working on some Cloudant/Couchdb stuff recently and thanks for reminding, will complete the remaining doc no later than tomorrow.

**Comment by jannyHou** [comment]
Unfortunately I don't have enough time this week to work on the embeds polymorphic relation doc, so I only applied feedback regarding:

- Change model name
- Refactor definition format

@crandmck @ebarault PTAL, thanks.

**Comment by crandmck** [comment]
LGTM.  
Shall we merge this now, and open another PR for the embeds polymorphic relation changes?

**Comment by jannyHou** [comment]
@crandmck sure, merged. Thanks!

**Pull request merged**
