### PR TITLE
Update Environment-specific-configuration.md

### PR DESCRIPTION
**Pull request by Aman-Aalam**
For beginners in Node/Express.js, it's tough to know how to test environment variables locally. This small addition indicates how to do that. Suggestions welcomed

### CODE REVIEW

**Comment by virkt25** [comment]
@Sheikh-Aman Can you please sign the CLA & change the commit message so the 2nd line isn't over 72 characters.

**Comment by Aman-Aalam** [comment]
I changed the commit message, but somehow the checks didn't re-run.
Can I force re-run the checks somehow?

**Review by virkt25 — APPROVED** [review]

**Review by shimks — APPROVED** [review]

**Comment by virkt25** [comment]
Thanks for your contribution @Sheikh-Aman. Your PR has landed 🎉 

For future, the checks re-ran but actually failed on the commit message as we follow the 50/72 rule (50 characters first line, 72 on all subsequent lines). I fixed the commit message for you and have landed it.

**Comment by Aman-Aalam** [comment]
Thanks @virkt25 , thanks for the guidance and the help :)

**Pull request merged**
