### PR TITLE
Issue 434

### PR DESCRIPTION
**Pull request by lancedouglas1**
Linking to StackOverflow example of a nested delete.
https://github.com/strongloop/loopback.io/issues/434

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bschrammIBM** [comment]
Assigning to Eng team for a review.

**Comment by dhmlau** [comment]
@bschrammIBM , quick question.. Do we usually directly reference posts from SO in official documentation?

**Comment by bschrammIBM** [comment]
No it does not appear that there are other direct references to an example on www.StackOverflow.com. IMO not a good idea as we do not have control over the referenced page. There is, however, a reference to SO as a place to ask questions on this page: https://loopback.io/doc/en/contrib/Reporting-issues.html and as a community forum for lb on this page: https://loopback.io/doc/en/contrib/

In this case, could we rewrite the example to include it in the loopback.io?

**Comment by dhmlau** [comment]
@lancedouglas1 , per comment from @bschrammIBM , it would be a better approach if we could get a snippet of the example instead of referencing a link in the documentation.  Please feel free to submit a PR for the concrete example.  
With this reason, I'm closing this PR.  Thanks.

**Pull request closed without merging**
