### PR TITLE
Add documentation about options.http.path in model definition > relations

### PR DESCRIPTION
**Pull request by fgarit**
I was looking for a solution to alter the default path of a relation and I stumbled apon this solution which I believe was not documented.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bschrammIBM** [comment]
Thank you for submitting this edit. We are taking a look at it now and will confirm shortly.

**Comment by bschrammIBM** [comment]
Please sign the CLA for loopback here:
https://cla.strongloop.com/agreements/strongloop/loopback.io

**Review by jannyHou — APPROVED** [review]
hi @Flo-G is there any related code PR in loopback for your suggested feature?

(horrible....I could not change it to a comment or request change....sorry for the duplicate message)

**Review by jannyHou — CHANGES_REQUESTED** [review]
hi @Flo-G is there any related code PR in loopback for your suggested feature?

**Comment by fgarit** [comment]
Hi @jannyHou I can look for such a PR but I was just basing this on my experience working with the framework.

Here's my configuration:
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",

Edit: to be honest, it feels like it would take a really deep dive into the code to find the related pull request and I am not sure when I can find the time to do this.

**Comment by bajtos** [comment]
@jannyHou this feature has been supported for ages. I think I actually added it myself here: https://github.com/strongloop/strong-remoting/pull/37, see also https://github.com/strongloop/loopback-datasource-juggler/commit/dbb7c6d9ae91ed2c7ca42b961277742f70afbbb9

**Comment by bajtos** [comment]
Actually, my comment applies to `options.http.path` for top-level models. This documentation change is for relation options. Here is the line which handles that relation option: [lib/model.js#L537](https://github.com/strongloop/loopback/blob/fdb453943ab1f2514507172e4b282545acf57c67/lib/model.js#L537). This feature was added by https://github.com/strongloop/loopback/pull/427 AFAICT.

**Review by bajtos — APPROVED** [review]

**Review by jannyHou — APPROVED** [review]
I see, thank you! LGTM, just please fix the commit message to pass the lint:

```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    6ed1892 - Add information about options.http.path: line 3 longer than 72 characters.
**
**************************************************
```

**Review by bschrammIBM — CHANGES_REQUESTED** [review]
approved after commit message is fixed

**Comment by bajtos** [comment]
I fixed the commit message while running "squash and merge".

Thank you @Flo-G for the contribution! 🎉

**Pull request merged**
