### PR TITLE
I've started translating to Japanese.

### PR DESCRIPTION
**Pull request by t-eimizu**
deleted unnecessary files.
fixed invalid encoding (cp932 => UTF-8)
fixed layout (translate => page)
added all pages for convinience.
changed tag from Japanese to English.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bschrammIBM** [comment]
Can you please describe the changes you made for the Japanese translation? It looks like you translated the sidebar and top nav bar. Are there any other changes?

**Comment by t-eimizu** [comment]
I translated some pages:

- index.md
- Creating-an-application.md
- Discovering-models-from-relational-databases.md
- Environment-specific-configuration.md
- Getting-started-with-LoopBack.md
- Installation.md
- Standard-project-structure.md
- includes/Standard-project-structure.md
- Using-database-transactions.md

And I'm translating other pages.

**Comment by bschrammIBM** [comment]
Great! Do you think it makes sense to wait until you are finished, or to merge these edits incrementally?

**Comment by t-eimizu** [comment]
I think that prefer to merge incrementally for Japanese users.

**Review by bschrammIBM — APPROVED** [review]
OK to merge - we need to provide a Japanese version.

**Comment by t-eimizu** [comment]
Thaks a lot.

**Comment by t-eimizu** [comment]
Can anyone merge this PR?
I have no write access to this  repository.

**Pull request merged**
