### PR TITLE
Pt br translation

### PR DESCRIPTION
**Pull request by jaimeneeves**
Pt br translation

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
Hi @dejaneves thanks for the PR.  Can you please sign the CLA? 
https://cla.strongloop.com/agreements/strongloop/loopback.io

**Comment by jaimeneeves** [comment]
@crandmck , done !

**Comment by crandmck** [comment]
Wow, thanks that was fast :-)

Thanks very much for translation help.  I apologize that I haven't documented details of the translation process better...  I have a couple more requests. :-)

It's better not to copy untranslated English files into the `pt-br` directory for two reasons:
- The content of the English files may change, so you should always translate from the latest English version instead of the copied (possibly stale) version.
- Every additional file requires processing to build the site, so having lots of unused files slows down the site build with no benefit.

The `pt-br_lb2_sidebar.yml` sidebar shows that you've translated four additional files, so those should be the only ones in the `pt-br` directory.  If someone navigates to an untranslated file, sidebar will show standard page that says the page hasn't yet been translated with a link to the English page.  In general, `pt-br` directory should only contain files that have at least some Portuguese content in them.

Also, you only have a LB 2.x sidebar, but have also copied all the `en` LB3 files to `pages/pt-br/lb3/` but the sidebar doesn't link to them, so they are unused (not linked to).  If you want to translate LB3 content as well, then you should have a `pt-br_lb3_sidebar.yml` file also, with links to the translated 3.0 files.... For now, I suggest removing the `pages/pt-br/lb3/` folder and all the files in it.

We're kind of figuring out the translation process as we go.... Thanks again for helping!

**Comment by jaimeneeves** [comment]
OK, I will create another PR with the fix, so you can close this PR ?

**Comment by crandmck** [comment]
Sure, thanks!

**Pull request closed without merging**
