### PR TITLE
Repairing anchors

### PR DESCRIPTION
**Pull request by doublemarked**
I noticed a heap of broken anchor links and hacked together a script that fixed many of them. I've checked most of these fixes and they seem to work.

FYI, in the process I noticed some other cross-document links that are broken. A more comprehensive search and fix for broken links is probably required.

### CODE REVIEW

**Comment by crandmck** [comment]
Thanks!  A comprehensive search for broken links is a great idea, but not sure how to go about it.  Can we just run a link-checker on the site?

**Comment by doublemarked** [comment]
Yes, it should be fairly easy to identify broken links, though some trouble may come in trying to identify the correct targets. It's a process that may be a hassle to automate, but easy enough to do manually (though tedious).

**Comment by crandmck** [comment]
I can help with the "correcting the targets" part.  @doublemarked It would be awesome if you could help with the "identifying broken links" part. I opened #44 for this general task...thanks!

**Comment by doublemarked** [comment]
Sure, I can give it a look!

**Pull request merged**
