### PR TITLE
Add Change Password Manual

### PR DESCRIPTION
**Pull request by mekuanent**
A manual for Change password method in UserRepository for the Android SDK. Which the code is in pull request now.

### CODE REVIEW

**Comment by crandmck** [comment]
@mekuanent Thanks for the PR.  Did you sign the CLA?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by mekuanent** [comment]
@crandmck Thanks. I did now

**Comment by crandmck** [comment]
Thanks @mekuanent !

**Pull request merged**
