### PR TITLE
Update Bluemix docs

### PR DESCRIPTION
**Pull request by hacksparrow**
Added new content or updated existing content about Bluemix integration.

### CODE REVIEW

**Comment by hacksparrow** [comment]
NOTE: please do not land this yet.

**Comment by crandmck** [comment]
Thanks @hacksparrow Just FYI, I will be out on vacation for the next two weeks.
In my absence, I suggest @bschrammIBM reviews this for writing, clarity, etc.

Since it still says "do not land" you should wait until it's ready @bschrammIBM.

**Comment by bschrammIBM** [comment]
@hacksparrow Are these edits ready to "land"?

**Comment by hacksparrow** [comment]
Closing in favor of https://github.com/strongloop/loopback.io/pull/421

**Pull request closed without merging**
