### PR TITLE
Add governance sections with list of maintainers

### PR DESCRIPTION
**Pull request by crandmck**
@altsang Here is the new info on governance and maintainers.

### CODE REVIEW

**Comment by altsang** [comment]
looks like loopback-boot is listed twice on the modules - we should have `loopback` as the first core module, can add more later, otherwise :+1:

**Comment by crandmck** [comment]
Good catch.  I fixed that.  The file I checked in has the "badges" described in my last comment in #14 commented out in the HTML.  If you want to check it out for yourself, clone the branch and remove the comment section in `contributing/index.html`.

**Comment by crandmck** [comment]
@altsang Can we go ahead and merge this with just the bullet list of maintainers? 

I'll come back to the task of making them look like "cards" which will take a bit more time (the HTML for that is commented out currently).  But I don't think we need to hold up this whole thing for that....

**Comment by altsang** [comment]
:+1:

On Thu, Mar 5, 2015 at 10:28 AM, Rand McKinney notifications@github.com
wrote:

> @altsang https://github.com/altsang Can we go ahead and merge this with
> just the bullet list of maintainers?
> 
> I'll come back to the task of making them look like "cards" which will
> take a bit more time. But I don't think we need to hold up this whole thing
> for that....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strongloop/loopback.io/pull/16#issuecomment-77420559.

## 

Al Tsang
Co-Founder and CTO @ StrongLoop, Inc.

_StrongLoop http://strongloop.com/_\* makes it easy to **develop APIs
http://strongloop.com/mobile-application-development/loopback/** in Node,
plus get DevOps capabilities
http://strongloop.com/node-js-performance/strongops/ like monitoring,
debugging and clustering*_._

**Pull request merged**
