### PR TITLE
updating external readmes

### PR DESCRIPTION
**Pull request by Sequoia**
Related to changes precipitated by discussion on #49

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by Sequoia** [comment]
(I ran `npm run fetch-readmes` & committed the resulting new versions of those files)

**Comment by Sequoia** [comment]
Incidentally, should that be run automatically on blog build? is that possible? Is this blog built by github?

**Comment by crandmck** [comment]
> Incidentally, should that be run automatically on blog build? is that possible? Is this blog built by github?

Yes, it's automatically rebuilt whenever you commit to the gh-pages branch, and I don't know how we would trigger this.  As we discussed, running manually is OK for now.

**Pull request merged**
