### PR TITLE
Remove Twitter section in footer

### PR DESCRIPTION
**Pull request by psjnek**
@dhmlau 
This pull request removes the Twitter buttons as requested.

### CODE REVIEW

**Comment by dhmlau** [comment]
@WebSnke, thanks for the PR. Could you please sign the DCO? You can amend the commit message using the following command to sign the commit:
```
git commit --amend -s
```

**Comment by psjnek** [comment]
> @WebSnke, thanks for the PR. Could you please sign the DCO? You can amend the commit message using the following command to sign the commit:
> 
> ```
> git commit --amend -s
> ```

I just amended the commit through GitHub Desktop on Windows.

**Comment by dhmlau** [comment]
@WebSnke, hm... it doesn't seem to quite work. If the commit is signed, it will look something like below on GitHub (see the `Signed-off-by` text):

Screenshot 2023-10-10 at 9 42 52 AM

The other way would be to add the text `Signed-off-by: <your email address>` as the second line of the commit. 
Hope it works for you this time. Thanks.

**Comment by psjnek** [comment]
> @WebSnke, hm... it doesn't seem to quite work. If the commit is signed, it will look something like below on GitHub (see the `Signed-off-by` text):
> Screenshot 2023-10-10 at 9 42 52 AM
> 
> The other way would be to add the text `Signed-off-by: <your email address>` as the second line of the commit. Hope it works for you this time. Thanks.

It didn't really work for me. I tried to right click the commits to amend them but without success...
What do I do wrong?

**Comment by dhmlau** [comment]
I can see that the 2nd commit was signed, but not the first commit :)
Can you squash the commits and make sure the commit left is signed? It's getting close!

**Comment by psjnek** [comment]
I will open a new pull request and add amend the commits by adding the respective message to the commit message.

**Comment by dhmlau** [comment]
thanks! I've kicked off CI on your other PR. Will merge when it passes.

**Pull request closed without merging**
