### PR TITLE
enable package-locks

### PR DESCRIPTION
**Pull request by dhmlau**
Enable package-locks

cc @raymondfeng

### CODE REVIEW

**Review by raymondfeng — APPROVED** [review]

**Comment by raymondfeng** [comment]
DCO is missing. After this PR, we probably should also use `npm ci` instead of `npm install` in other scripts.

**Comment by dhmlau** [comment]
> After this PR, we probably should also use npm ci instead of npm install in other scripts.

@raymondfeng, do you mean this https://github.com/strongloop/loopback.io#incorporating-external-readmes?

**Comment by raymondfeng** [comment]
> @raymondfeng, do you mean this https://github.com/strongloop/loopback.io#incorporating-external-readmes?

Please note `npm ci` uses `package-lock.json` to ensure only versions in the lock file are used for repeatable behaviors. In addition to docs, we should check `*.js` files in this repo and `loopback-next/docs` repo to see if we use `npm i` for `loopback.io`.

**Comment by dhmlau** [comment]
I checked the js files at the root level and in `js` folder, I don't see them using `npm install`.

**Pull request merged**
