### PR TITLE
fix: remove gray text in navbar links

### PR DESCRIPTION
**Pull request by Neverage**
Remove gray text in navbar links for mobile devices
nav

### CODE REVIEW

**Comment by dhmlau** [comment]
@Neverage, thanks for the PR. I'd like to run the site locally to see the changes in effect. However, I'm having some problems in running `bundle install` after upgrading my MacOS to Big Sur.  Looking to resolve my machine problem..

**Comment by Neverage** [comment]
Thank you. Good luck solving the problem

**Comment by achrinza** [comment]
I've managed to test from my end.

**Current:**
image

**New:**
image

**Review by achrinza — APPROVED** [review]

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@Neverage, thanks for your contribution. Your PR has landed! 
FYI - I rebased and landed the PR before the bot lands another PR and make this out of date again.

**Comment by Neverage** [comment]
@achrinza, @dhmlau, thank you.

**Pull request merged**
