### PR TITLE
docs: juggler security advisory

### PR DESCRIPTION
**Pull request by virkt25**
Security Advisory for juggler.

### CODE REVIEW

**Review by kjdelisle — APPROVED** [review]

**Comment by shimks** [comment]
Add in sidebar entries please

**Review by jannyHou — APPROVED** [review]
👍

**Review by bschrammIBM — APPROVED** [review]

**Comment by bajtos** [comment]
@virkt25 please post a message to https://groups.google.com/forum/#!forum/loopbackjs-announcements. If there is any checklist of tasks needed to fix a security issue, then please add this step to that list.

**Comment by virkt25** [comment]
I don't have access to post there it seems (or I don't know how to use Google Groups).

**Comment by bajtos** [comment]
@virkt25 I elevated your privileges so that you can post now. Can you try again please?

**Comment by virkt25** [comment]
Done :)

**Pull request merged**
