### PR TITLE
Reworked sidebar menu

### PR DESCRIPTION
**Pull request by Sequoia**
# New Menu Schema

I made all the sidebars I could find in `_data/sidebars` match the new, simplified schema.

`topnav.yml` still uses the old scheme because
1. it needs `external_url`
2. it doesn't use the same (sidebar) template so there's no conflict
# Performance

The new setup increases build time from ~18 seconds to ~25 seconds. Initially it was over 30 seconds but I did what I could to trim that time down (mostly removing `assign`s). Lots of the info I found said "reduce the number of `for` loops" but that's simply not an option here-- the menu is a tree and each level must be stepped thru.

I spent time with various profiling tools but they didn't do much beyond verify that yes, it's the loops that are causing the performance hit. I have the CPU profiles if anyone wants to look thru them! 😸 
screen shot 2016-09-29 at 1 55 27 pm
## Things that might help
1. Incremental builds if we could get it working
2. Cached includes plugin (build the menu 1x per build & cache it for all pages, would require setting `active` class from front-end, fairly trivial). I investigated building such a plugin but it looked like it would take too long. [more info](https://talk.jekyllrb.com/t/caching-includes/3036)
3. Manually "caching" the sidebar. Essentially, making a separate build task just for the sidebar, running it when sidebar changes, then `{%include%}`ing the _built_ output.
# Other languages

As these currently have no language-specific content (they are just placeholder files, essentially, waiting to be translated), I simply overwrote them with thew new LB 2 menu scheme.
# PDFs

I left the PDF templates alone for now. Getting PDF generation to work is a whole 'nother task that will take some time (see [instructions](idratherbewriting.com/documentation-theme-jekyll/mydoc_generating_pdfs.html)). When it's decided that we want to do this, it shouldn't be difficult to update the PDF templates to match the new sidebar template.

Files that I did not update:
- `scripts-pdf/pdfconfigs/tocpage.html`
- `scripts-pdf/pdfconfigs/prince-list.txt`

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by Sequoia** [comment]
closes #66

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
Will review ASAP, thanks Sequoia!

**Comment by crandmck** [comment]
This looks great, in general.  It will give us more flexibility in structuring the document hierarchy, and is much easier to work with because the YAML format is simpler and more consistent.

There are some problems with the changes you made to the localized sidebars, though.  Specifically:
- Russian and Japanese had some translated titles (in the `yml` sidebar file), which were lost.
- You replaced the urls of all translated articles with `en` URLs, but I migrated over some translated articles from the old doc site (the content still needs some cleanup, but it's there).  Only two in `ja` but a bunch in `ru`. 

Can you fix these before I merge?

**Comment by crandmck** [comment]
@Sequoia I need to do some other stuff, so I'll go ahead and merge this and fix the above-noted issues, nbd.

**Pull request merged**
