### PR TITLE
Conversion of original content to MD

### PR DESCRIPTION
**Pull request by marc-ed-raffalli**
PR for [Migrate Conflunce content to markdown #29 ](https://github.com/strongloop/loopback.io/issues/29)
- converted HTML to MD
- added images
- updated lb2 side bar

### CODE REVIEW

**Comment by marc-ed-raffalli** [comment]
No sure what is the issue, the commit has the line "Signed-off-by: Marc-Ed Raffalli <raffalli.marc@hotmail.fr>"

**Comment by crandmck** [comment]
Wow, thanks!  Give a little time to have a look at this, as it's very big :-)

**Comment by marc-ed-raffalli** [comment]
Haha, not the kind to go half way ;-)

I reviewed the files generated output and verified the links/images were working on Jekyll in general. 
Also did some tidy up when I could catch typo or code issues.
- JSON and JS prettified
- verified code syntax flag javascript for JS and JSON, shell for commands, else blank

## Conversion report:

### Could not match docs link

```
"Advanced topics: data sources"         https://docs.strongloop.com/display/LB/Advanced+topics%3A+data+sources in file Connecting-models-to-data-sources_9634166.html
"API Explorer"                          https://docs.strongloop.com/display/LB/API+Explorer in file LoopBack-components_9634230.html
"API Explorer"                          https://docs.strongloop.com/display/LB/API+Explorer in file LoopBack-components_9634230.html
"API Explorer"                          https://docs.strongloop.com/display/LB/Use+API+Explorer in file Environment-specific-configuration_9634215.html
"API Explorer"                          https://docs.strongloop.com/display/LB/Use+API+Explorer in file Exposing-models-over-REST_9634132.html
"API Explorer"                          https://docs.strongloop.com/display/LB/Use+API+Explorer in file Preparing-for-deployment_9634352.html
"API Explorer"                          https://docs.strongloop.com/display/LB/Use+API+Explorer in file Security-considerations_9634209.html
"Application generator"                 https://docs.strongloop.com/display/LB/Application+generator in file Environment-specific-configuration_9634215.html
"application generator"                 https://docs.strongloop.com/display/LB/Application+generator in file LoopBack-components_9634230.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file LoopBack-components_9634230.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file LoopBack-components_9634230.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file LoopBack-components_9634230.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file LoopBack-components_9634230.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file Project-layout-reference_9634278.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file Project-layout-reference_9634278.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file Project-layout-reference_9634278.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file Standard-project-structure_9634218.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file Standard-project-structure_9634218.html
"component-config.json"                 https://docs.strongloop.com/display/LB/component-config.json in file Standard-project-structure_9634218.html
"CRUD operations"                       https://docs.strongloop.com/display/LB/Creating%2C+updating%2C+and+deleting+data in file 10354945.html
"CRUD operations"                       https://docs.strongloop.com/display/LB/Creating%2C+updating%2C+and+deleting+data in file DashDB_10354947.html
"CRUD operations"                       https://docs.strongloop.com/display/LB/Creating%2C+updating%2C+and+deleting+data in file Informix_10354949.html
"data source generator"                 https://docs.strongloop.com/display/LB/Data+source+generator in file 10354945.html
"data source generator"                 https://docs.strongloop.com/display/LB/Data+source+generator in file DashDB_10354947.html
"data source generator"                 https://docs.strongloop.com/display/LB/Data+source+generator in file Informix_10354949.html
"DataSource generator"                  https://docs.strongloop.com/display/LB/Data+source+generator in file REST-connector_9634192.html
"Extend your API"                       https://docs.strongloop.com/display/LB/Extend+your+API in file Remote-methods_9634262.html
"Getting started with LoopBack"         https://docs.strongloop.com/display/LB/Getting+started+with+LoopBack in file Android-SDK_9634112.html
"Getting started with LoopBack"         https://docs.strongloop.com/display/LB/Getting+started+with+LoopBack in file AngularJS-JavaScript-SDK_9634121.html
"Getting started with LoopBack"         https://docs.strongloop.com/display/LB/Getting+started+with+LoopBack in file Introduction-to-User-model-authentication_9634213.html
"LoopBack API Explorer"                 https://docs.strongloop.com/display/LB/Use+API+Explorer in file LoopBack-components_9634230.html
"Part 2"                                https://docs.strongloop.com/display/LB/Creating+a+LoopBack+iOS+app%3A+part+two in file 9634118.html
"part one"                              https://docs.strongloop.com/display/LB/Creating+a+LoopBack+iOS+app%3A+part+one in file 9634117.html
"Part two"                              https://docs.strongloop.com/display/LB/Creating+a+LoopBack+iOS+app%3A+part+two in file 9634118.html
"Tutorial: access control"              https://docs.strongloop.com/display/LB/Tutorial%3A+access+control in file 9634204.html
"Use API Explorer"                      https://docs.strongloop.com/display/LB/Use+API+Explorer in file LoopBack-components_9634230.html
"Use API Explorer"                      https://docs.strongloop.com/display/LB/Use+API+Explorer in file LoopBack-components_9634230.html
```

### No text for link

```
https://gist.github.com/bajtos/63b415629a341ef5d0c9#checkpoints                                                                 in Synchronization_9634251.html
https://gist.github.com/bajtos/63b415629a341ef5d0c9#conflict-detection                                                          in Synchronization_9634251.html
https://gist.github.com/bajtos/63b415629a341ef5d0c9#create-a-client-app                                                         in Synchronization_9634251.html
https://gist.github.com/bajtos/63b415629a341ef5d0c9#enable-change-tracking                                                      in Synchronization_9634251.html
https://gist.github.com/bajtos/63b415629a341ef5d0c9#replication-algorithm                                                       in Synchronization_9634251.html
https://gist.github.com/bajtos/63b415629a341ef5d0c9#run-the-client-app-in-the-browser                                           in Synchronization_9634251.html
https://gist.github.com/bajtos/b8157112452eeaf984c9#before-save                                                                 in 10354716.html
https://gist.github.com/bajtos/b8157112452eeaf984c9#before-save                                                                 in Operation-hooks_9634261.html
https://gist.github.com/bajtos/e7eaba736ff096916b71#error-handling-middleware                                                   in Defining-middleware_9634267.html
https://gist.github.com/fabien/7d4ed2c9fcd815e0703f#hasandbelongstomany                                                         in Polymorphic-relations_9634134.html
https://gist.github.com/fabien/7d4ed2c9fcd815e0703f#hasmany                                                                     in Polymorphic-relations_9634134.html
https://gist.github.com/fabien/7d4ed2c9fcd815e0703f#hasone                                                                      in Polymorphic-relations_9634134.html
https://gist.github.com/fabien/7d4ed2c9fcd815e0703f#properties                                                                  in Creating-model-relations_9634133.html
https://gist.github.com/fabien/7d4ed2c9fcd815e0703f#scope                                                                       in Creating-model-relations_9634133.html
https://gist.github.com/ritch/f9b264642174dbef3831#options-object                                                               in Model-definition-JSON-file_9634289.html
https://github.com/ibm-apiconnect/cli#api-designer                                                                              in Getting-started-with-the-Developer-Toolkit-command-line-tool_9635106.html
https://github.com/strongloop/loopback-android/blob/master/docs/GettingStarted.md#android-studio-setup                          in Android-SDK_9634112.html
https://github.com/strongloop/loopback-android/blob/master/docs/GettingStarted.md#eclipse-adt-setup                             in Android-SDK_9634112.html
https://github.com/strongloop/loopback-android/blob/master/docs/GettingStarted.md#getting-started-with-the-loopback-sdk         in Android-SDK_9634112.html
https://github.com/strongloop/loopback-android/blob/master/docs/GettingStarted.md#troubleshooting                               in Android-SDK_9634112.html
https://github.com/strongloop/loopback-android/blob/master/docs/GettingStarted.md#working-with-the-sdk                          in Android-SDK_9634112.html
https://github.com/strongloop/loopback-android/blob/master/docs/Subclassing.md#prerequisites                                    in Android-SDK_9634112.html
https://github.com/strongloop/loopback-android/blob/master/docs/Subclassing.md#step-1-model-class--properties                   in Android-SDK_9634112.html
https://github.com/strongloop/loopback-android/blob/master/docs/Subclassing.md#step-3-model-repository                          in Android-SDK_9634112.html
https://github.com/strongloop/loopback-android/blob/master/docs/Subclassing.md#step-5-a-little-glue                             in Android-SDK_9634112.html
https://github.com/strongloop/loopback-android/blob/master/docs/Subclassing.md#step-6-profit                                    in Android-SDK_9634112.html
https://github.com/strongloop/loopback-component-oauth2#authorization-server-options                                            in OAuth-2.0_9634255.html
https://github.com/strongloop/loopback-component-oauth2#custom-functions-for-token-generation                                   in OAuth-2.0_9634255.html
https://github.com/strongloop/loopback-component-oauth2#examples                                                                in OAuth-2.0_9634255.html
https://github.com/strongloop/loopback-component-oauth2#key-building-blocks                                                     in OAuth-2.0_9634255.html
https://github.com/strongloop/loopback-component-oauth2#protect-endpoints-with-oauth-20                                         in OAuth-2.0_9634255.html
https://github.com/strongloop/loopback-component-oauth2#server-types                                                            in OAuth-2.0_9634255.html
https://github.com/strongloop/loopback-component-oauth2#supported-grant-types                                                   in OAuth-2.0_9634255.html
https://github.com/strongloop/loopback-component-oauth2#usage                                                                   in OAuth-2.0_9634255.html
https://github.com/strongloop/loopback-connector-postgresql/blob/master/README.md#auto-migrate--auto-update                     in PostgreSQL-connector_9634184.html
https://github.com/strongloop/loopback-connector-postgresql/blob/master/README.md#discovering-models                            in PostgreSQL-connector_9634184.html
https://github.com/strongloop/loopback-connector-postgresql/blob/master/README.md#json-to-postgresql-types                      in PostgreSQL-connector_9634184.html
https://github.com/strongloop/loopback-connector-postgresql/blob/master/README.md#postgresql-types-to-json                      in PostgreSQL-connector_9634184.html
https://github.com/strongloop/loopback-connector-postgresql/blob/master/README.md#type-mapping                                  in PostgreSQL-connector_9634184.html
https://github.com/strongloop/loopback-connector-soap/blob/master/README.md#extend-a-model-to-wrapmediate-soap-operations       in SOAP-connector_9634196.html
https://github.com/strongloop/loopback-connector/blob/master/docs/sql-connector.md#understand-a-connectors-responsibilities     in Building-a-connector_9634170.html
https://github.com/strongloop/loopback-example-angular                                                                          in AngularJS-Grunt-plugin_9634123.html
https://github.com/strongloop/loopback-example-angular                                                                          in AngularJS-JavaScript-SDK_9634121.html
https://github.com/strongloop/loopback-faq-user-management#notes-2                                                              in LoopBack-FAQ_9634358.html
https://github.com/strongloop/loopback/blob/production/docs/api-model-remote.md#ctxreqaccesstoken                               in Remote-hooks_9634263.html
https://github.com/strongloop/loopback/blob/production/docs/api-model-remote.md#ctxresult                                       in Remote-hooks_9634263.html
```

**Comment by crandmck** [comment]
OK, this is fantastic!  Thank you so much!  

I'm going to merge it, but I'd like to know how much manual post-processing / editing you did.  Because we've continued to work on the [current docs](https://docs.strongloop.com) since I exported the space, we'll need to reconvert the changed (and some new) files. 

Also, are you going to contribute your conversion script/code?  (I didn't see it in your fork/branch). In addition to the updates mentioned above, we'll need to use it some more--both to convert the translated docs (French, German, Chinese, etc) and almost certainly there will be additional English files that somehow got left out that we'll want to convert.

If you're willing to contribute it (I hope so!), we can discuss whether it makes sense to keep it in this repo or put it in a separate repo.

**Comment by marc-ed-raffalli** [comment]
Great !

I'll create a separate repo with the converter script and make it available with a set of instructions.

The post processing is very minor. Mostly to check the readability, code blocks are correctly beautified and it detected the language correctly. The `...` for example causes js verification to fail.

**Comment by crandmck** [comment]
Great, I'll look for your note. Thanks again!

**Comment by marc-ed-raffalli** [comment]
I pushed the converter to a separate repo: https://github.com/marc-ed-raffalli/confluence-to-jekyll

Updated the description of the complete conversion flow.

**Comment by crandmck** [comment]
For ease of reference, I copied the "Conversion report" (above) to https://github.com/strongloop/loopback.io/wiki/Issues-with-conversion.

**Pull request merged**
