### PR TITLE
Update HasAndBelongsToMany-relations.md in LB3

### PR DESCRIPTION
**Pull request by canmustu**
update HasAndBelongsToMany-relations.md in LB3

### CODE REVIEW

**Comment by dhmlau** [comment]
@canmustu, just a nitpick. Could you please update the commit message to match the changes? A suggestion would be:
```
update HasAndBelongsToMany-relations.md in LB2
```

Other than that, your PR is good to go. Thanks!

**Comment by canmustu** [comment]
@dhmlau I think we have 1 more problem with Commit Linter :) Should I create a new PR if this PR couldn't be mergeable by commit names being more than 50 ?

**Comment by dhmlau** [comment]
Could you please squash the commits? I think the commit linter issue is coming from the `Merge branch ...` commit messages.

**Comment by canmustu** [comment]
I pull requested https://github.com/strongloop/loopback.io/pull/1082 here. Sorry for these problems. @dhmlau

**Pull request closed without merging**
