### PR TITLE
Updated link, was getting routed to 404 page

### PR DESCRIPTION
**Pull request by shyd0w**
fixes linking for dependency injection

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by shyd0w** [comment]
just was bothered by the incorrect linking, while i was reading, hope this helps! thanks so much for all the help in the past with loopback 💯

**Comment by kjdelisle** [comment]
@shyd0w If you sign the CLA (https://cla.strongloop.com/agreements/strongloop/loopback.io) we can merge this!

(It's just some legal stuff we have to do to accept your change.)

**Comment by shyd0w** [comment]
I believe i signed it, please let me know 👍  😃

**Review by bschrammIBM — APPROVED** [review]
Link is fixed, thanks for catching this.

**Comment by dhmlau** [comment]
@shyd0w , thanks for the PR.  Looks like the link has been fixed.

**Pull request closed without merging**
