### PR TITLE
Update footer copyrights for 2020

### PR DESCRIPTION
**Pull request by shivaylamba**
Updated copyright for the year 2020.

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@shivaylamba, thanks for your PR.  Could you please sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback.io. Thanks!

**Comment by shivaylamba** [comment]
@dhmlau i have signed the CLA

**Comment by shivaylamba** [comment]
@dhmlau Is there any other requirement for the PR to be merged?

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
Thanks @shivaylamba. Your PR has landed! 🎉

**Pull request merged**
