### PR TITLE
Add Bank of America Logo

### PR DESCRIPTION
**Pull request by rosshj**
Status: **OPEN FOR REVIEW**
Owner: @rosshj
Reviewers: @altsang @crandmck 
## Changes
- [x] Remove Sapient logo
- [x] Add Bank of America logo
## Jira Tickets:
- n/a
## Todos:
- [ ] Designer / Engineer +1
### Feedback:

_none so far_
## How to Test
- Take a look at the home page 'Check out who's using LoopBack!' section and make sure the Sapient logo has been replaced by the Bank of America logo.

### CODE REVIEW

**Comment by crandmck** [comment]
LGTM.  @altsang Do you want to check it out, or shall I just merge it?

**Comment by altsang** [comment]
go for it thx!

On Mar 16, 2015, at 8:54 AM, Rand McKinney notifications@github.com wrote:

LGTM. @altsang https://github.com/altsang Do you want to check it out, or
shall I just merge it?

**Comment by crandmck** [comment]
Thanks, Ross!

**Comment by altsang** [comment]
Thanks Ross!  Looks fantastic!

**Pull request merged**
