### PR TITLE
Issue302

### PR DESCRIPTION
**Pull request by bschrammIBM**
This fix contains the edits for issue 302, disableRemoteMethod changed to disableMethodByName in 3.0.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
LGTM, thanks!

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
BTW, don't be alarmed at the inclusion of updates to files in the `readmes` directory.  These changes are automatically made by our Jenkins pipeline based on changes to READMEs in other repos.  They got pulled in to your commit when you did a `git pull` to bring your branch up to date with master.

**Pull request merged**
