### PR TITLE
fix: set sidebar input field as per query value

### PR DESCRIPTION
**Pull request by rahulrkr08**
Updating sidebar input field setting from query value.

#808

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]
I'd like to get at least one more reviews before landing.
@nabdelgadir, since you've worked with loopback.io recently, PTAL? Thanks.

**Review by nabdelgadir — COMMENTED** [review]
@rahulrkr08 Thanks for the contribution! It's still redirecting to `lb3_sidebar` with this change for me. I see the problem is the query (https://github.com/strongloop/loopback.io/blob/335e83c7caf0b2f672c1e98190d0579af971cfa2/_layouts/search.html#L69) is changing to `sidebar` to `lb3_sidebar` with every new search.

**Comment by rahulrkr08** [comment]
@nabdelgadir Sorry, my bad type error. Wrongly given input field name as 'search-bar' instead of 'sidebar'. I re-committed, please check.

**Review by nabdelgadir — APPROVED** [review]
Works now, thank you! 💯 

Can you please squash the commits and rebase your PR? And then I'll merge.

**Comment by rahulrkr08** [comment]
@nabdelgadir I am facing some issue on merging commits, will raise new PR.

**Pull request closed without merging**
