### PR TITLE
chore: update ejs url

### PR DESCRIPTION
**Pull request by achrinza**
see https://github.com/strongloop/loopback-next/issues/4872#issuecomment-598964368

Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]
Thanks for fixing that, @achrinza!

**Comment by dhmlau** [comment]
@bajtos, the commit linter complains about exceeding the 72-character limit. Do you think it's ok to merge it anyway? 
Or @achrinza, is it ok for you to remove the "sign off" message? The commit itself has your authorship. 

Thanks.

**Comment by achrinza** [comment]
@dhmlau It's both the GitHub link and the sign-off.

I'm not sure if the character limit should apply to the body commit message, as GitHub wraps that text automatically. This would also probably add friction to the adoption of DCO.

I've updated the commit message.

**Comment by dhmlau** [comment]
@achrinza, I realized you don't have merge rights on this repo, so I went ahead to land the PR for you. Thanks again! 🎉

**Comment by dougal83** [comment]
@achrinza Brilliant. Thank you!

**Pull request merged**
