### PR TITLE
fix: better responsive transition of toolbar

### LINKED ISSUE #1005: loopback.io header not collapsed for mobile
## URL of the page 

Reported by a user from Slack channel: https://loopbackio.slack.com/archives/C01177XQN8N/p1592276970025300, 

Image from iOS

The navbar does collapse after certain point eventually.. on desktop. :)

### PR DESCRIPTION
**Pull request by hacksparrow**
Fixes https://github.com/strongloop/loopback.io/issues/1005.

**BEFORE**
before

**AFTER**
after

### CODE REVIEW

**Comment by raymondfeng** [comment]
I'm curious what's behind `991px` over `768px`.

**Comment by hacksparrow** [comment]
@raymondfeng The side menu is progammed to adjust for smaller screens (from 991px onwards) by jumping to the top of the page. The navigation bar also does similar adjustments, but from 768px onwards, instead of 991px - they are not in sync. This PR makes the navigation bar to start adjusting itself from 991px onwards.

I also explored the option of doing this adjustment from 768px, but the content of the navigation bar is too much to be contained within 768px, so 991px it is.

**Review by dhmlau — APPROVED** [review]
Verified on my laptop, and seems to be working.
Haven't got a chance to try it on the phone.

**Comment by hacksparrow** [comment]
@dhmlau do you want to wait till confirming on the phone? It should just work.

**Comment by dhmlau** [comment]
If you've verified it on the phone, please feel free to land the PR. Thanks.

**Pull request merged**
