### PR TITLE
Update Using-MongoLab.md

### PR DESCRIPTION
**Pull request by atherdon**
Small update, 'cause we don't have previous link url - mongolab.com
Maybe it'll be necessary to update title and permalink, but not sure.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
Thanks!  It would make sense to change the title.  Could you please do this?  Then, I'll land the PR.

The permalink doesn't matter as much, but you can change it if you wish.

**Comment by atherdon** [comment]
Hi @crandmck, ok will do!
I think change permalink is not necessary, because it can ruin google index(maybe).
I propose to add some clarification. On title I'll add "*" sign to make things clear - MongoLab == mLab

**Comment by atherdon** [comment]
Question: I tried to copy paste code from this page to my datasource file and got an issue "Cannot create data source "nameDS": DataSource option "defaultForType" is no longer supported".
So I came to this link: https://stackoverflow.com/a/21655979
I test this solution and it works well for me. Can I change this code sample on readme page too?

**Comment by crandmck** [comment]
Yes, please do remove `defaultforType`.  It was removed in v3 (see https://loopback.io/doc/en/lb3/3.0-Release-Notes.html#loopbackautoattach-removed).

Thanks for testing it and catching this.

**Comment by atherdon** [comment]
Done, please check @crandmck

**Comment by crandmck** [comment]
Thanks!

**Pull request merged**
