### PR TITLE
Updated Remote-methods.md

### PR DESCRIPTION
**Pull request by karthicktv**
Replaced - with + due to the string getting concatenated. Came across this issue while I was testing the docs for Remote methods for my project

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
Good catch!  Thanks for the PR.
@karthicktv Will you please sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback.io

**Comment by karthicktv** [comment]
@crandmck  Thanks. CLA signed.

**Comment by crandmck** [comment]
Thanks!!

**Comment by crandmck** [comment]
Thanks!

**Pull request merged**
