### PR TITLE
Initialize documentation Chinese translation files for Loopback 4

### PR DESCRIPTION
**Pull request by mikefoxnobel**
And translated a few topics.

### CODE REVIEW

**Comment by dhmlau** [comment]
@nabdelgadir @agnes512, could you please help reviewing this PR? Thanks!

**Review by nabdelgadir — COMMENTED** [review]
Thanks for the translations! I noticed you translated some files and the others are the English ones. Right now, we have it set up so that if there's no translation, it will link to the English version anyway. To make this PR easier to review, would you mind removing any non-translated pages? Thank you!

**Comment by mikefoxnobel** [comment]
Removed files which are not translated.
But images are still keeping.

**Comment by mikefoxnobel** [comment]
@dhmlau @nabdelgadir @agnes512 
Sorry for that, because my wrong merge and rebase, this PR is too bad.
I will close this PR and create a new clear one.

**Comment by agnes512** [comment]
Here's a PR for reference https://github.com/strongloop/loopback.io/pull/841. Hope it's helpful. Thank you!

**Pull request closed without merging**
