### PR TITLE
Update functional-area-owners.md

### PR DESCRIPTION
**Pull request by superkhau**
@crandmck PTAL

### CODE REVIEW

**Comment by superkhau** [comment]
cc @ritch @cgole

**Comment by crandmck** [comment]
This change in and of itself is fine, but I need to understand what's happening to these example repos that you removed from the list.  The docs currently use some of these READMEs (see https://github.com/strongloop/loopback.io/blob/gh-pages/update-readmes.sh) so if they will no longer be maintained we should remove them.  But I wonder if we have replacement examples?

**Comment by superkhau** [comment]
>But I wonder if we have replacement examples?

Nope, we should move most of the content to loopback.io if possible -- they will remain in strongloop-community for reference though (I'm trying to get us to take advantage of strongloop-community more instead of using it as a dumping ground for dead projects).

**Comment by crandmck** [comment]
OK, I think I misunderstood.  These repos are not going away, but rather just got moved into strongloop-community org, right?  If so, we can continue to use the READMEs as we do, but just change the location where we get them from.

**Pull request merged**
