### PR TITLE
Update Accessing-related-models.md

### PR DESCRIPTION
**Pull request by marlonnelson**
Method arguments seem to have changed.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Review by bschrammIBM — APPROVED** [review]
LGTM

**Comment by bajtos** [comment]
@marlonnelson good catch! The example looks like it is describing API exposed by our AngularJS SDK.

**Comment by bajtos** [comment]
Landed, thank you!

**Pull request merged**
