### PR TITLE
Document relations options property

### PR DESCRIPTION
**Pull request by frankorama**
Documenting the options property that can be defined in a model relation.  Thus far I have only found one property for options.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
@frankorama Thanks for the PR.  

Did you mean to add this only for v2?  I wouldn't think it's specific to v2.
To also add it to LoopBack v3 docs, edit `pages/en/lb3/Model-definition-JSON-file.md`.

Also, rather than putting the options in a "table within a table" which is awkward and can be hard to read, since there's only one options property, I suggest just documenting the property as `options.disableInclude`.  

And one small nitpick: Boolean is always capitalized :-)

**Comment by frankorama** [comment]
@crandmck Thanks for the feedback.  My first pull-request.  I'll make the changes to v2 (and change the case on 'Boolean')

Cheers.

**Comment by crandmck** [comment]
Thanks!  Could you please also address this:
> rather than putting the options in a "table within a table" which is awkward and can be hard to read, since there's only one options property, I suggest just documenting the property as options.disableInclude.

**Comment by crandmck** [comment]
Great, LGTM!

**Pull request merged**
