### PR TITLE
Add dynamodb connector to the sidebar

### PR DESCRIPTION
**Pull request by mandarzope**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
Please sign the CLA https://cla.strongloop.com/agreements/strongloop/loopback.io

**Comment by crandmck** [comment]
@mandarzope We can't land your commits until you agree to the CLA....
Can you please do that?

**Comment by mandarzope** [comment]
Hi,
@crandmck I have already signed the CLA. 
Let me know if its not reflecting there. 
I can see on CLA page
"
Agreements you have signed:
strongloop/loopback.io
"
Thanks
Mandar

**Comment by crandmck** [comment]
It is now, thank you!!

**Pull request merged**
