### PR TITLE
Fix broken docs #1055 Signed-off-By: E. Wray Johnson<wray.johnson@gmail.com>

### PR DESCRIPTION
**Pull request by ewrayjohnson**
This resolves an critical (IMHO) issue that has been broken for a long time but a PR offered by another contributor was never approved/merged.  It is such a simple fix.

### CODE REVIEW

**Comment by dhmlau** [comment]
@ewrayjohnson, thanks for the PR. The PR #1055 wasn't merged because the contributor hasn't signed the DCO yet, which is the pre-requisite to land a PR. I've pinged the author of the PR to see if they are able to sign.

**Comment by ewrayjohnson** [comment]
> @ewrayjohnson, thanks for the PR. The PR #1055 wasn't merged because the contributor hasn't signed the DCO yet, which is the pre-requisite to land a PR. I've pinged the author of the PR to see if they are able to sign.

That's why I submitted the same fix under my own PR which I tried singing mine using the same instructions you provided them, but the instructions did not work for me.

**Comment by raymondfeng** [comment]
@ewrayjohnson `Signed-off-by:` should be part your commit message instead of the title of the PR. See https://loopback.io/doc/en/contrib/code-contrib.html#signing-off-commits-using-dco.

**Comment by ewrayjohnson** [comment]
> @ewrayjohnson `Signed-off-by:` should be part your commit message instead of the title of the PR. See https://loopback.io/doc/en/contrib/code-contrib.html#signing-off-commits-using-dco.

I tried that but there's a limit to the number of characters of the commit message that's too small.

**Comment by ewrayjohnson** [comment]
> > @ewrayjohnson `Signed-off-by:` should be part your commit message instead of the title of the PR. See https://loopback.io/doc/en/contrib/code-contrib.html#signing-off-commits-using-dco.
> 
> I tried that but there's a limit to the number of characters of the commit message that's too small.

I also tried to amend the commit message but was unsuccessful.

**Comment by raymondfeng** [comment]
@ewrayjohnson If you grant me the permission (in a reply to this comment), I can help amend your commit and push back to your branch.

**Comment by ewrayjohnson** [comment]
> @ewrayjohnson If you grant me the permission (in a reply to this comment), I can help amend your commit and push back to your branch.

I hereby grant you the permission

**Review by raymondfeng — APPROVED** [review]
@ewrayjohnson Thank you for the contribution and patience.

**Pull request merged**
