### PR TITLE
Japanese version for 5 pages.

### PR DESCRIPTION
**Pull request by saotak**
Working on the Japanese translation for Loopback 4. Not fully translated yet though, I am going to 
update the Japanese pages. So please accept the pull request for this branch. 

File title example;
JP_: Translation has done but some format is not fully optimized yet.
INPROGRESS_ : Translation is in progress.

### CODE REVIEW

**Comment by dhmlau** [comment]
@saotak, thanks for translating the documentation! 
Please keep in mind that since none of our maintainers can read Japanese, we cannot verify the translation. We also remind the users that the translation is a community effort.  For some reason, that note in LB4 Japanese version is not visible, I'll look into it. 

To move this PR forward, could you please:
- make this PR only contains the files that have translation completed. Feel free to create another PR for the in-progress ones
- sign the CLA https://cla.strongloop.com/agreements/strongloop/loopback.io
- rebase the PR so that it's up to date

Thanks.

**Comment by saotak** [comment]
@dhmlau , Thanks a lot for your response! Noted, I sighed up CLA and cleaned the requested branch only with completed files. I already pushed the changes though, the pull request seems blocked (Probably because of the conflict of index.md with your side). Could you check with it again maybe?
Thanks!

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@saotak, I fixed the conflicting changes on your branch and rebased. 
Thanks again for your contribution. Your PR has landed! 🎉

**Comment by saotak** [comment]
@dhmlau , Thank you so much for accepting the PR! Give me a moment to upload additional files completed :)

**Pull request merged**
