### PR TITLE
Change OASGraph to OpenAPI-to-GraphQL

### PR DESCRIPTION
**Pull request by ErikWittern**
Signed-off-by: Erik Wittern <witternj@us.ibm.com>

### CODE REVIEW

**Comment by agnes512** [comment]
LGTM 👍

**Review by agnes512 — APPROVED** [review]

**Review by nabdelgadir — APPROVED** [review]
LGTM 👍

**Comment by nabdelgadir** [comment]
Thanks for the contribution!

**Comment by ErikWittern** [comment]
Thank you for the super-fast acceptance!

**Pull request merged**
