### PR TITLE
Improve UX and grammar of docs

### PR DESCRIPTION
**Pull request by foladipo**
This PR:
- fixes some typos or grammatical errors I found while reading through some of the docs.
- adds a link to the `loopback-getting-started` repo.

### CODE REVIEW

**Review by shimks — APPROVED** [review]

**Comment by dhmlau** [comment]
@foladipo, thanks for the PR.  Could you please sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback.io
Also, it looks like the PR is out of date.  Please rebase.  Other than that, it's good to go!

**Comment by dhmlau** [comment]
@foladipo  thanks for signing the CLA.  Could you please rebase your branch too? thanks!

**Comment by foladipo** [comment]
I have rebased this PR from my computer, but your Linter is still saying it's out of date. And I don't like the idea of signing up for yet another GitHub app so as to see the details of that error. So please help me out.

That said, I think your contribution rules are way too difficult. I have contributed to many open-source projects, from Elasticsearch and Kotlin to ReactionCommerce, and never have I had to go through such an involved process just to freely add value to an open-source repo. I think y'all need to look into simplifying that process.

Regards.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by shimks** [comment]
It seems to be a problem with the CI considering github's telling us that there shouldn't be any conflicts. @rmg Could you take a look at what might be happening here?

**Comment by dhmlau** [comment]
@foladipo , thanks for your contribution and feedback.  It looks like there's some hiccups in our CI which indicated your PR was out-of-date where it wasn't.

**Comment by foladipo** [comment]
Roger that.

**Pull request merged**
