### PR TITLE
Update HasManyThrough-relations.md

### PR DESCRIPTION
**Pull request by Tobmai**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Review by bschrammIBM — CHANGES_REQUESTED** [review]
Can you please provide an explanation for why this change is needed?

**Comment by dhmlau** [comment]
@jannyHou , PTAL?

**Review by jannyHou — APPROVED** [review]
LGTM

**Comment by bschrammIBM** [comment]
Here is link to the page:
https://loopback.io/doc/en/lb3/HasManyThrough-relations.html

**Review by bschrammIBM — APPROVED** [review]

**Comment by jannyHou** [comment]
Hi @bschrammIBM, I think the reason is we created the instance with `{patientId: 1}`: https://github.com/strongloop/loopback.io/pull/544/files#diff-7b5f81ba00268175654aba0eb0bd4e26L324, so it makes sense that we also query with the same value `1`

**Comment by Tobmai** [comment]
@jannyHou exactly. 
Additionally in a sample response (https://loopback.io/doc/en/lb3/HasManyThrough-relations.html) we got "patientId: 1", not "patientId: 2" like in GET query.
```
[
  {
    "appointmentDate": "2014-06-01",
    "id": 1,
    **"patientId": 1,**
    "physicianId": 1,
    "patient": {
      "name": "Jane Smith",
      "id": 1
    }
  }
]
```

**Pull request merged**
