### PR TITLE
Update soap-calculator-tutorial-add-controller.md

### PR DESCRIPTION
**Pull request by dougal83**
Correct erroneous @param 'arg2'

### CODE REVIEW

**Comment by dougal83** [comment]
https://github.com/strongloop/loopback-next/issues/3060

**Comment by nabdelgadir** [comment]
Thanks for the contribution! The change looks good, but should be made in https://github.com/strongloop/loopback-next/blob/master/docs/site/tutorials/soap-calculator/soap-calculator-tutorial-add-controller.md instead because this page on the loopback.io repo gets copied over from loopback-next. You can read about it [here](https://loopback.io/doc/en/contrib/doc-contrib.html#how-loopback-documentation-works) if you're interested.

**Comment by dougal83** [comment]
Thanks for the info.  I'll close assuming you've handled it.

**Comment by nabdelgadir** [comment]
@dougal83 I actually left it for you if you wanted to open another PR (see [this comment](https://github.com/strongloop/loopback-next/pull/3081#discussion_r292044574)), but if you want, I can update it. Just let me know 😄

**Comment by dougal83** [comment]
Please go ahead and make the update yourself. I tried to be helpful to save
time and failed. 😁

**Comment by nabdelgadir** [comment]
@dougal83 sounds good, thanks!

**Pull request closed without merging**
