### PR TITLE
Cleanup of HTML/CSS + Users page

### PR DESCRIPTION
**Pull request by rosshj**
Status: **OPEN FOR REVIEW**
Owner: @rosshj
Reviewers: @altsang @crandmck 
## Changes
- [x] General HTML/CSS cleanup
- [x] Create proper component for blockquote
- [x] Adjust modifiers to use proper syntax
- [x] Fix issues on the Users/Customers page
- [x] New customer callout on home page
## Jira Tickets:
- n/a
## Todos:
- [x] Designer +1
- [x] Engineer +1
### Feedback:

_none so far_
## How to Test
- Look through the HTML and CSS changes. Do they look good?
- Take a look at the /users page and make sure everything is looking good on both desktop and mobile.
- **WIP** Look at the home page. Does the callout look ok and does it have faint logos present in the background?

### CODE REVIEW

**Comment by crandmck** [comment]
The PR looks OK, with two exceptions:

@altsang specifically asked that the customer/logo page have a white background, because the logos we have are meant to be viewed vs. a light bg (see http://loopback.io/users/).   I don't think they look good with the "standard" dark gray background:
loopback io-userpage

I also prefer the way the testimonial quotes stand out (in light gray boxes) in the current look of the site, but that's just IMO.

Also, is there enough contrast in the "logo collage" on the home page (see below)?  Personally, I think the logos should be lighter so they stand out a bit more:
lb user logos

**Comment by altsang** [comment]
+1 to what @crandmck brought up.  He actually had the gray page with the white back icons and it looked very much like a cut and paste job (which it clearly is!)  I also agree and  think the testimonials could stand out better and that the contract is very light on the collage.

**Comment by rosshj** [comment]
@altsang @crandmck Hmmm. I'm not getting the grey background.

screen shot 2015-02-17 at 7 52 44 pm

Silly question, did you try emptying your browser cache? I changed a fair amount of CSS, the part to look for is...

```
.x-white {
    background: #fff;
}
```

Re: Customer callout. I agree. I had a feeling it was too subtle. I will look into some way of addressing the prominence of it.

**Comment by crandmck** [comment]
Yep, you're right it was a css browsing issue.  Once I cleared the cache, it looks fine.

Let me know when you've addressed the other issue, an--assuming it looks ok--we can merge this..ty.

**Comment by crandmck** [comment]
@rosshj  I added a section on contributing to the project to `resources/index.html` as requested by @altsang.  I don't think that will affect anything else, but I believe Al wants it up ASAP.

**Comment by rosshj** [comment]
@altsang @crandmck 

The users/customers callout on the home page is now more prominent and with a CTA to prompt the user.

screen shot 2015-02-18 at 9 52 18 pm

I'll take a look into that other request around a new section next.

**Comment by crandmck** [comment]
LGTM, thx!

**Pull request merged**
