### PR TITLE
Closed parenthesis

### PR DESCRIPTION
**Pull request by kanrio**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by raymondfeng** [comment]
@rmg The CLA link is broken - https://www.clahub.com/agreements/strongloop/loopback.io. Can you take a look?

**Comment by rmg** [comment]
@raymondfeng thanks for the heads up. A small bug related to the recent outage. I've fixed it and the link in the status is now correct.

**Comment by raymondfeng** [comment]
@anouarkacem Please sign CLA at https://cla.strongloop.com/agreements/strongloop/loopback.io

**Comment by kanrio** [comment]
@raymondfeng I signed thank you

**Review by bschrammIBM — APPROVED** [review]

**Pull request merged**
