### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by kulshekhar**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Review by dhmlau — APPROVED** [review]
LGTM

**Comment by dhmlau** [comment]
@bschrammIBM, I've landed this PR because it's fixing the URL in the doc.  hope you don't mind.

**Comment by dhmlau** [comment]
@kulshekhar, thanks for your contribution!

**Comment by kulshekhar** [comment]
That was fast! And you're welcome :)

**Pull request merged**
