### PR TITLE
Typo: Dangling comma before closing square bracket

### PR DESCRIPTION
**Pull request by logesh-kumar**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
@logesh-kumar Will you please sign the CLA?
https://cla.strongloop.com/agreements/strongloop/loopback.io

**Review by kjdelisle — APPROVED** [review]
@logesh-kumar Once you sign the CLA that @crandmck linked, we can land this PR.

**Comment by raymondfeng** [comment]
@logesh-kumar Please sign CLA - https://cla.strongloop.com/agreements/strongloop/loopback.io

**Comment by logesh-kumar** [comment]
Done

**Review by bschrammIBM — APPROVED** [review]
Please merge your edit!

**Pull request merged**
