### PR TITLE
improve lb4 repository docs

### PR DESCRIPTION
**Pull request by haoxins**

### CODE REVIEW

**Review by crandmck — COMMENTED** [review]
This looks reasonable to me, but I'd like someone else to take a quick look...

@kjdelisle perhaps?

**Review by kjdelisle — COMMENTED** [review]
I like the changes to the imported repository names (makes the examples easier to parse), but I noticed that we're changing `Product` to `Account` in some other examples. Given that we're changing the Repositories.md to use `ProductRepository`, wouldn't it be more consistent to have all of those items remain as `Product` instances? Alternatively, you could change `ProductRepository` to be `AccountRepository` to get the same effect.

Looks good, though. Approachable examples are key! :+1:

**Comment by haoxins** [comment]
> Alternatively, you could change ProductRepository to be AccountRepository to get the same effect.

DONE :)

**Review by kjdelisle — APPROVED** [review]

**Comment by kjdelisle** [comment]
LGTM

**Pull request merged**
