### PR TITLE
Correct the datasource name for coffeeShop model

### PR DESCRIPTION
**Pull request by Amir-61**
* Correct the datasource name for coffeeShop model

Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1356

/to: @crandmck, PTAL, thanks!
/cc: @cgole

### CODE REVIEW

**Review by cgole — CHANGES_REQUESTED** [review]
The name of the DS should be mysqlDS and the change should be made in the script portion of the doc here.. Change app.dataSources.mysqlDs.automigrate to app.dataSources.mysqlDS.automigrate

**Comment by Amir-61** [comment]
Hey @cgole 

>Change app.dataSources.mysqlDs.automigrate to app.dataSources.mysqlDS.automigrate

Sorry I'm not clear why you are proposing to change `mysqlDs` to `mysqlDS` in `/server/boot/create-sample-models.js`; please note, you called your mysql datasource `mysqlDs` [here](http://loopback.io/doc/en/lb3/Connect-your-API-to-a-data-source.html#configure-data-source):
```
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "mysqlDs": {
    "name": "mysqlDs",
    "connector": "mysql",
    "host": "demo.strongloop.com",
    "port": 3306,
    "database": "getting_started",
    "username": "demo",
    "password": "L00pBack"
  }
}
```

So the same name needs to be used in `/server/boot/create-sample-models.js` as well:
```
...
 app.dataSources.mysqlDs.automigrate('CoffeeShop', function(err) {
...
```

Apart from that in this PR I made the doc more clear for changing the datasource name to `mysqlDs` for `CoffeeShop` model.

**Comment by crandmck** [comment]
@Amir-61 @cgole I'm preoccupied with the 3.0 updates.  Can you psl clarify if I should merge this "as is" or if further changes are needed?

**Comment by Amir-61** [comment]
>@Amir-61 @cgole I'm preoccupied with the 3.0 updates. Can you psl clarify if I should merge this "as is" or if further changes are needed?

Yes @cgole is reviewing the changes here. I assigned it to @cgole for review.

**Comment by crandmck** [comment]
I finished the other work and had a chance to review this.  It's correct, so I'll go ahead and merge it.

**Pull request merged**
