### PR TITLE
Add french language for LB4

### PR DESCRIPTION
**Pull request by Yaty**
Hello,

I finally got some time for LB4 :)
I'll start working & maintaining the French documentation if you're ok !

### CODE REVIEW

**Comment by dhmlau** [comment]
Thanks @Yaty! :) 
@bschrammIBM, probably need your help to review.  
We usually have some text at the top of the community translated documentation that `This is a community translation into French. For the latest information, see the English version.`  @bschrammIBM can probably point to where/how it can be added. 

See https://loopback.io/doc/fr/lb2/ as an example.

**Comment by Yaty** [comment]
This is already done here when the translation is marked as done : https://github.com/strongloop/loopback.io/blob/062c44542da4d29bfbd877f26e89b560b253bbfb/_layouts/translation.html#L16

**Review by bschrammIBM — APPROVED** [review]
approved, the disclaimer is inserted
However, I think you are in the wrong repo for updating LB4 docs.
@biniam Can you confirm where translations should be checked in for LB4 docs?

**Comment by dhmlau** [comment]
@b-admike is the right github handle. :)     
Could you please help?  Thanks.

**Comment by b-admike** [comment]
@bschrammIBM The docs content in loopback-next at https://github.com/strongloop/loopback-next/tree/master/docs/site are copied over to the `/pages/en/lb4` directory (see https://github.com/strongloop/loopback.io/blob/gh-pages/update-lb4-docs.js#L4-L5). So, if we want this patch to be contributed there, we would have to create a new directory structure there (perhaps under site we have `en` and `fr` in loopback-next) and modify the scripts to copy them over properly. @strongloop/sq-lb-apex @bajtos @raymondfeng thoughts?

**Comment by bajtos** [comment]
@Yaty This is awesome ❤️ ❤️ ❤️ 

> So, if we want this patch to be contributed there, we would have to create a new directory structure there (perhaps under site we have en and fr in loopback-next) and modify the scripts to copy them over properly. @strongloop/sq-lb-apex @bajtos @raymondfeng thoughts?

We are keeping LB4 docs in loopback-next for two reasons:
 - To allow pull requests to update both the code and the relevant docs
 - To delay doc updates until the code changes are published to npm

IMO, the translations should be versioned independently of the main English content, it's unrealistic to expect loopback-next pull requests to update translated versions too. Therefore I think this repository (`loopback.io`) is the right place for LB4 translations.

**Comment by b-admike** [comment]
@bajtos Thanks for the clarification and yea I agree we should put translations in this repo 👍. Thank you for the contribution @Yaty LGTM as well.

**Review by b-admike — APPROVED** [review]

**Comment by dhmlau** [comment]
Merging this PR since we got approval from @b-admike and @bschrammIBM.
@Yaty, thanks for your contribution! 🎉

**Pull request merged**
