### PR TITLE
Update Model-definition-JSON-file.md

### PR DESCRIPTION
**Pull request by osk2**
Remove unclosed tag.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
Hm, this line was removed by https://github.com/strongloop/loopback.io/commit/c1af56d8da13bbb2d97f77d18b8d6ee513f729c7#diff-d77cc751a988ac25b9809ecc13fde871

@bajtos or @loay Can you confirm that `$related principalId` is now implemented?

**Comment by ebarault** [comment]
@crandmck Built-in role $related is not implemented yet

**Comment by crandmck** [comment]
Thanks @ebarault I wonder why that note (that it's not implemented) was removed?  I'll reinstate it.

**Comment by crandmck** [comment]
Just to confirm @ebarault it's not implemented in v3 as well?  I just noticed that this PR is for LB v2 only...

**Pull request merged**
