### PR TITLE
Update HasAndBelongsToMany-relations.md

### PR DESCRIPTION
**Pull request by canmustu**
Optionally we can set table name ( collection name for mongoDB ) custom.

### CODE REVIEW

**Comment by dhmlau** [comment]
@canmustu, thanks for the PR. Looks like we had it in the LB2 docs https://loopback.io/doc/en/lb2/HasAndBelongsToMany-relations.html but not LB3. :) 

Could you please sign the commit with DCO?  Just in case, here is the instruction: https://loopback.io/doc/en/contrib/code-contrib.html#signing-off-commits-using-dco.

**Comment by canmustu** [comment]
I tried to clone this repo to commit `sign-off` but I got error. Do you have any idea about this problem to fix ? After this process, no file is shown in folder so I can not see any file to change. @dhmlau 

I tried to delete forked repo and reforked, still same.

```
> git clone https://github.com/canmustu/loopback.io.git

Cloning into 'loopback.io'...
remote: Enumerating objects: 656, done.
remote: Counting objects: 100% (656/656), done.
remote: Compressing objects: 100% (287/287), done.
remote: Total 32405 (delta 320), reused 505 (delta 298), pack-reused 31749
Receiving objects: 100% (32405/32405), 131.85 MiB | 2.60 MiB/s, done.
Resolving deltas: 100% (24893/24893), done.
error: invalid path 'pages/zh/lb4/tutorials / todo/todo-tutorial-controller.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by dhmlau** [comment]
Hm... I'm not sure. I just tried to fork this repo and git clone it. It seems to be working fine: 
```
$ git clone https://github.com/dhmlau/loopback.io.git
Cloning into 'loopback.io'...
remote: Enumerating objects: 656, done.
remote: Counting objects: 100% (656/656), done.
remote: Compressing objects: 100% (287/287), done.
remote: Total 32405 (delta 320), reused 505 (delta 298), pack-reused 31749
Receiving objects: 100% (32405/32405), 131.85 MiB | 30.81 MiB/s, done.
Resolving deltas: 100% (24893/24893), done.
Checking out files: 100% (5193/5193), done.
```

I clicked the fork button on the top right corner to fork the repo, just in case it matters.

**Comment by canmustu** [comment]
Yes, I forked with that button on my last try too. I am gonna check this problem out. I think that it is about a git config which I am not sure. Maybe path max-length limit config or something else.

**Comment by dhmlau** [comment]
Just curious.. are you on Windows? 
It's extra space in the folder names for the chinese version. I submitted PR #1080 to fix it. Hope it will work for you after the PR has landed.

**Comment by dhmlau** [comment]
@canmustu, my PR #1080 has landed. Could you please try forking the repo again? Thanks.

**Review by tanselOzkusaksiz — APPROVED** [review]

**Comment by canmustu** [comment]
Yes, I'm on Windows10. I just reforked the repo and everthing is working well now.

The new PR is here : https://github.com/strongloop/loopback.io/pull/1081

I close this PR now.

**Pull request closed without merging**
