### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by b1az**
Minor improvements for LB3 docs.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by b1az** [comment]
https://github.com/strongloop/loopback.io/pull/364/commits/2a939b8ca06d27e40ad8f6c017990918215daa96 should address #363.

**Comment by crandmck** [comment]
Thanks @b1az for catching all these!
Only one thing isn't obvious: Why did you remove the video from [Managing users](http://loopback.io/doc/en/lb3/Managing-users.html)?

**Comment by b1az** [comment]
@crandmck, I explained the video removal in the commit message:
> Its bad audio quality casts a negative light on LoopBack

I'll drop this commit if you want this video to stay.

(I do see the value of having some videos interspersed in the docs, but didn't dare pick a worthy replacement myself.)

**Comment by crandmck** [comment]
OK, sorry I didn't notice the commit message....

I think you're right, the audio is bad.  So, I'm OK with removing it.
Thanks!

**Pull request merged**
