### PR TITLE
Fix broken docs

### LINKED ISSUE #1003: Broken documentation page (Model-definition-JSON-file)
## URL of the page 

Github: https://github.com/strongloop/loopback.io/blob/gh-pages/pages/en/lb3/Model-definition-JSON-file.md
Site: https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html

## Nature of the issue 

All documentation content after "Data mapping properties" section is not displayed in documentation site (but persists in Github)

## Expected behavior

Github page content is equal to documetation on the site.

## Actual behavior

More then half of the page is missing

## Suggested resolution

Fix the markdown on the page, then check and fix your parser to prevent silent data corruption like this one.

### PR DESCRIPTION
**Pull request by ismirnov-ekoniva**
Closes #1003

### CODE REVIEW

**Comment by ismirnov-ekoniva** [comment]
I am created this PR from Github UI. Is it possible to sign-off comit without setting up a git/cloning repository and so on? If not - is there a way to skip/cancel "sign-off pre-commit check"?

**Comment by dhmlau** [comment]
@ismirnov-ekoniva, thanks for the PR. You can sign off the commit by adding the following in the commit message:
```
Signed-off-By: YourName<YourEmail>
```

I also found a Chrome extension https://chrome.google.com/webstore/detail/dco-github-ui/onhgmjhnaeipfgacbglaphlmllkpoijo?hl=en, but haven't tried it. 

Hope it helps.

**Review by ewrayjohnson — APPROVED** [review]
Signed-off-By: E. Wray Johnson<wray.johnson@gmail.com>

**Comment by dhmlau** [comment]
@ismirnov-ekoniva, did you have a chance to review my [above comment](https://github.com/strongloop/loopback.io/pull/1055#issuecomment-680091428) in signing DCO? 
You can also find more details in https://loopback.io/doc/en/contrib/code-contrib.html. Thanks.

**Comment by dhmlau** [comment]
Closing in favor of #1061.

**Pull request closed without merging**
