### PR TITLE
Translation of LB4 docs to portuguese

### PR DESCRIPTION
**Pull request by newtonsbm**
- Initial configuration for a new language (pt-br / LB4)
- Translated index.md

### CODE REVIEW

**Comment by bschrammIBM** [comment]
Thank you for the translation, I have forwarded it to the technical team.

**Review by bschrammIBM — CHANGES_REQUESTED** [review]
Please add the following statement in English on the index.md page  "This is a community translation into Portuguese. For the latest information, see the English version."  "English version" should be a hyperlink to http://loopback.io/doc/en/lb4/index.html

**Comment by dhmlau** [comment]
@newtonsbm , thanks for translating the documentation for LB4!  Please keep in mind that LB4 is in Developer Preview #1, therefore there might be lots of changes in a near future.  Stay tuned!

Could you please rebase your PR and fix the commit messages?  It shows the 2 messages below exceed the 50 characters limit.  Thanks.
```
Linting commit logs
**
**  2 problems found:
**    b98cfa7 - adds a warning about the community translation to p: First line should be 50 characters or less (saw 55)
**    be821a8 - Merge branch 'gh-pages' of github.com:strongloop/lo: First line should be 50 characters or less (saw 74)
**
```

**Review by bschrammIBM — APPROVED** [review]

**Comment by bschrammIBM** [comment]
You will need to rebase so this can be merged.

**Comment by newtonsbm** [comment]
Ok, I've never done rebase before, I'm following this guide [here](https://loopback.io/doc/en/contrib/code-contrib.html) but it still did not work out. I think it's because I've merge at first. I will keep trying.

**Comment by dhmlau** [comment]
Looks like it worked!  Your PR has landed.  Thanks for your contribution!

**Pull request merged**
