### PR TITLE
adding Firebase Firestore

### PR DESCRIPTION
**Pull request by dyaa**
https://github.com/dyaa/loopback-connector-firestore

---
This change is [Reviewable](https://reviewable.io/reviews/strongloop/loopback.io/476)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
Thanks for the PR!  

We're happy to add your connector, but I'd prefer to link to the npmjs.com page, as the other connectors have done, rather than the GH repo.  Of course they actually have the same content, but for consistency and to make it clear that the pkg is available in npm.

(I just noticed that a couple link to the GitHub repo, and I'll correct that soon.  I thought I'd do it after your PR to avoid any merge conflicts).

**Comment by dyaa** [comment]
@crandmck Done

**Comment by dyaa** [comment]
any updates @crandmck

**Comment by crandmck** [comment]
Thanks!

**Comment by crandmck** [comment]
@dyaa JFYI, I edited the page to put your entry in the correct alphabetical order.  Hadn't noticed before that it wasn't....

**Pull request merged**
