### PR TITLE
Adding required to the ID argument

### PR DESCRIPTION
**Pull request by m4rii0**

### CODE REVIEW

**Comment by bschrammIBM** [comment]
m4rii0 - please sign the CLA and also fix your commit message in order to have this edit merged - Linting commit logs
**
**  1 problems found:
**    811a7cb - Adding required to the ID argument: line 3 longer than 72 characters.

**Comment by m4rii0** [comment]
I'm relatively new doing Pull Requests, how can I fix the commit message?
Thanks

**Comment by dhmlau** [comment]
@m4rii0 , you can use `git commit --amend` command.  See instructions for details: https://help.github.com/articles/changing-a-commit-message/.  Hope it helps.

**Comment by dhmlau** [comment]
@m4rii0 , sorry about the delay. I've fixed the commit message to you.  Thanks for your contribution.  Your PR has landed! 🎉

**Pull request merged**
