### PR TITLE
translated some pages into Japanese.

### PR DESCRIPTION
**Pull request by t-eimizu**
fixed invalid encoding (cp932 => UTF-8)
fixed layout (translate => page)
Add ja directory under _includes/content.
Copy files in _includes/content to _includes/content/ja.

### CODE REVIEW

**Comment by bschrammIBM** [comment]
@bajtos I think you requested these changes. Can you please review and approve?

**Review by bajtos — APPROVED** [review]
This is great, thank you @t-eimizu!

There are too many changes to review them in detail, plus I don't speak Japanese 🇯🇵  But since I don't see any obvious problems, I think we should go ahead and land this pull request.

**Review by bschrammIBM — CHANGES_REQUESTED** [review]
Please add the following statement in English on the index.md page "This is a community translation into Japanese. For the latest information, see the English version." "English version" should be a hyperlink to http://loopback.io/doc/en/lb3/index.html

**Comment by t-eimizu** [comment]
Hi, @bschrammIBM 

I've added the statement at the top of index.md.
Is this what you expected?

**Review by bschrammIBM — APPROVED** [review]

**Pull request merged**
