### PR TITLE
[Docs] Move the Security Advisories to loopback.io home page

### PR DESCRIPTION
**Pull request by bschrammIBM**
This project is part of https://github.com/strongloop/loopback-next/issues/2168. The Security Advisories should be on the main doc page, not just in the LoopBack 3 docs. The rationale is that the Security Policies apply to all versions.

### CODE REVIEW

**Comment by dhmlau** [comment]
@bschrammIBM, thanks for refactoring of the security advisories pages.  
Are you planning to remove the security advisories pages under https://github.com/strongloop/loopback.io/tree/gh-pages/pages/en/lb3 as a follow-up PR?

**Comment by bschrammIBM** [comment]
The Security Advisories are no longer available on LB3 site, but I do need to remove them from the sidebar nav and also from the repo. Good catch.

**Comment by dhmlau** [comment]
Actually the https://github.com/strongloop/loopback.io/tree/gh-pages/pages/en/lb3/Security-advisory*.md files still exist.

**Review by dhmlau — APPROVED** [review]
LGTM.  Please squash the commits before merging, also with the follow-up PR to clean up the duplicate security-advisory*.md files.  Thanks.

**Pull request merged**
