### PR TITLE
feat: sync LoopBack 4 EOL with Node.js v14 EOL

### PR DESCRIPTION
**Pull request by achrinza**
see https://github.com/strongloop/loopback-next/issues/6709

Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@bajtos, do you think we can update the commit linter to allow more than 72 characters per line? I believe loopback-next is less restrictive on the number of characters.

**Comment by dhmlau** [comment]
@achrinza, after discussing with @bajtos, we're planning to force merge your PR. Could you please rebase so that we can do that? Thanks.

**Comment by bajtos** [comment]
> do you think we can update the commit linter to allow more than 72 characters per line? I believe loopback-next is less restrictive on the number of characters.

I believe this should have been already fixed. Let me re-run the build.

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
Landed, thank you @achrinza for the contribution! ❤️

**Pull request merged**
