### PR TITLE
Replace Waffle with ZenHub in contrib/Governance

### PR DESCRIPTION
**Pull request by bajtos**
@chandadharap could you please review and approve?
@rand feel free to make any edits/improvements as you deem fit
cc @raymond @ritch @superkhau

### CODE REVIEW

**Review by superkhau — APPROVED** [review]

**Comment by crandmck** [comment]
Made some small formatting and spelling corrections.  LGTM.

**Review by crandmck — APPROVED** [review]

**Comment by ghost** [comment]
One small nit, do we want to mention that LB project is switching to ZenHub from Waffle, instead of just replacing the text mentioning Waffle? Or just go ahead with your text. You and @crandmck can decide. 

Otherwise LGTM.

**Comment by crandmck** [comment]
I added a short note stating that we switched from Waffle.  Will land this now.

**Comment by bajtos** [comment]
Lovely, thank you all for your help with getting this landed! ❤️

**Pull request merged**
