### PR TITLE
Update Defining-middleware.md

### PR DESCRIPTION
**Pull request by fcrisciani**
typo on the tracker code

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
Thanks!!

@fcrisciani Could you please sign the CLA?

**Comment by fcrisciani** [comment]
Sure, where can I find it?

**Comment by crandmck** [comment]
https://cla.strongloop.com/agreements/strongloop/loopback.io

**Comment by fcrisciani** [comment]
done

**Comment by crandmck** [comment]
Thanks @fcrisciani

**Pull request merged**
