### PR TITLE
Update Polymorphic-relations.md

### PR DESCRIPTION
**Pull request by zlm919**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by crandmck** [comment]
@jannyHou Can you review this please?  The other examples seem to have the `model` key, so not sure why it wouldn't apply here?

**Comment by jannyHou** [comment]
@crandmck  IMO the `model` will be ignored if `polymorphic` exists, see code https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L1221-L1222

So it's reasonable to remove it. `polymorphic` means it will lookup the related model dynamically.
Our test case in juggler also only specify the `relationName`: https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L1693

**Comment by jannyHou** [comment]
@zlm919 The change LGTM, can you sign the contribution agreement? Thanks. Then we can land this patch after CI check green.

**Pull request merged**
